apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cb-prototype-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: cb-prototype
  minReplicas:  1
  maxReplicas:  10
  targetCPUUtilizationPercentage: 50
